libata: Fix up semantic conflict in ata_scsi_set_sense()
/tmp/next/build/drivers/ata/libata-scsi.c: In function 'ata_scsi_pass_thru':
/tmp/next/build/drivers/ata/libata-scsi.c:3575:25: error: too many arguments to function 'ata_scsi_set_sense'
 3575 |                         ata_scsi_set_sense(dev, scmd, ABORTED_COMMAND, 0, 0);
      |                         ^~~~~~~~~~~~~~~~~~
/tmp/next/build/drivers/ata/libata-scsi.c:206:6: note: declared here
  206 | void ata_scsi_set_sense(struct ata_device *dev, struct scsi_cmnd *cmd,
      |      ^~~~~~~~~~~~~~~~~~

Signed-off-by: Mark Brown <broonie@kernel.org>